The example of code that defines `ket0` and `ket1`, corresponding to the qubit state vectors $|0\rangle$ and $|1\rangle$ respectively, and then calculate their average.

In [5]:
from numpy import array

ket0 = array([1, 0])
ket1 = array([0, 1])

display(ket0 / 2 + ket1 / 2)

array([0.5, 0.5])

`display()` is not necessary in this demo:

In [6]:
ket0 / 2 + ket1 / 2

array([0.5, 0.5])

Numpy's `array` can also be used to create matrices, which can represent operations in a system processing informations:

In [7]:
M1 = array([[1, 1], [0, 0]])
M2 = array([[1, 1], [1, 0]])

M1 / 2 + M2 / 2

array([[1. , 1. ],
       [0.5, 0. ]])

And it is also possible to do Matrix multiplication through Numpy's `matmul()` function:

In [8]:
from numpy import matmul

display(matmul(M1, ket1))
display(matmul(M1, M2))
display(matmul(M2, M1))

array([[1, 1],
       [1, 1]])

Note that only the last row of each cell is can be automatically displayed when not using `display()`. So in the case of the case above (for `matmul`), `display()` is still necessary, at least for `matmul(M1, ket1)` and `matmul(M1, M2)`.